### ISSUE TITLE
Search has a "page" arguement

### ISSUE THREAD

**Issue by Quantum-Codes** [wulliy/wasteof2-docs#10]
The last key of JSON data of https://api.wasteof.money/search/posts?q=e   ---> `last:false`.
Last key of https://api.wasteof.money/search/posts?q=e&page=3 ---> `last:true`

So page param exists

**Comment by Quantum-Codes** [comment]
Page 0 also there https://api.wasteof.money/search/posts?q=e&page=0

**Comment by wulliy** [comment]
thanks

**Comment by jeffalo** [comment]
page 0 is the same as page 1

**Comment by Quantum-Codes** [comment]
Oops,thanks
