### ISSUE TITLE
Why U Removed Wiki

### ISSUE THREAD

**Issue by AwesomePotato23** [wulliy/wasteof2-docs#11]
wiki was easier  to use :(

**Comment by Quantum-Codes** [comment]
Or maybe he is making a website? (github pages support markdown)

**Comment by Turtle84375** [comment]
Oh, that'd actually be even nicer... and if @jeffalo is willing to give a subdomain like docs.wasteof.money... :o

I'm getting ahead of myself lol

**Comment by Quantum-Codes** [comment]
He actually added github pages in a recent commit! I can't seem to get anything other than 404 pages tho :/

**Comment by TheAwesome98-Real** [comment]
he must not have, since the error isn't file not found, it's "there isn't a site here"

**Comment by TheAwesome98-Real** [comment]
clicking view-deployment doesn't work for some reason though

**Comment by Quantum-Codes** [comment]
> clicking view-deployment doesn't work for some reason though

Because the `gh-pages` branch is deleted. That branch had the content of the website

**Comment by TheAwesome98-Real** [comment]
oh

**Comment by wulliy** [comment]
😳

**Comment by TheAwesome98-Real** [comment]
> 😳

Willy it’s been 24 days please give us an update

**Comment by wulliy** [comment]
website

**Comment by TheAwesome98-Real** [comment]
yeah

**Comment by TheAwesome98-Real** [comment]
if Willy doesn’t do something soon:
![](https://i.imgflip.com/3dy5yp.png)

**Comment by wulliy** [comment]
ok

**Comment by TheAwesome98-Real** [comment]
oh no guys now i need to do it
