### ISSUE TITLE
Optimise parameter in banner

### ISSUE THREAD

**Issue by Quantum-Codes** [wulliy/wasteof2-docs#18]
> you can add ?optimzed=true to the end of the api endpoint for your banner if you want to get the optimized version of your banner that shows in the beta user card. so if you request /users/radi8/banner you get my animated trans flag banner but if you request /users/radi8/banner?optimized=true you get my campground banner :)

_source: https://alpha.wasteof.money/posts/64219398a3ca57347cf69465 (radi8)_

**Comment by doeyed** [comment]
thanks
