### ISSUE TITLE
You can do more than one image in a post now+another new endpoint

### ISSUE THREAD

**Issue by Oren-Lindsey** [wulliy/wasteof2-docs#9]
You can do more than one picture in post now, see this post: https://wasteof.money/posts/61dcbff259e4303b3f5d0c66
Also `GET https://api.wasteof.money/users/jeffalo/following/posts` gives you the posts made by the people a user is following

**Comment by wulliy** [comment]
> You can do more than one picture in post now, see this post: https://wasteof.money/posts/61dcbff259e4303b3f5d0c66

cool

> Also GET https://api.wasteof.money/users/jeffalo/following/posts gives you the posts made by the people a user is following

already exists
